### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/graclj#1]
Obviously the most important issue...

**Comment by ajoberstar** [comment]
Should still incorporate a [Grackle](https://en.wikipedia.org/wiki/Grackle).

**Comment by uklance** [comment]
FYI I've used fivesquid.com a couple of times to get logos designed for five pounds. Eg https://github.com/uklance/tader

**Comment by ajoberstar** [comment]
Good idea. Thanks!
